# Generated by Django 3.2 on 2023-07-11 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('priority', models.IntegerField(blank=True, choices=[(4, 'Urgent'), (3, 'High'), (2, 'Medium'), (1, 'Low')], default=1, verbose_name='priority')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='due date')),
                ('completed', models.BooleanField(blank=True, default=False, verbose_name='completed')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='completed date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
                'db_table': 'Tasks',
                'ordering': ['due_date', 'title'],
            },
        ),
    ]
